{
 "title": "monitoramento",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "SLA disponibilidade",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(100 * (sum(rate(flask_http_request_total[2m])) - sum(rate(flask_http_request_total{status=\"503\"}[2m])))  / sum(rate(flask_http_request_total[2m]))) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLA Time Response",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_bucket{le=\"0.5\"}[5m])) / sum(rate(flask_http_request_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disponibilidade por status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "increase(flask_http_request_total{status=\"200\"}[2m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(flask_http_request_total{status=\"503\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo de Reposta em %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_bucket{le=\"0.5\"}[5m])) / sum(rate(flask_http_request_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}